version: '2'
services:
  node_1:
    image: symetric-quorum-node
    environment:
      - KEEP_FILES=false
      - NODE_NAME=node1
      - CONSENSUS=istanbul
      - ROLE=coordinator
      - IP=172.14.0.2
    networks:
      three_node_quorum:
        ipv4_address: '172.14.0.2'
  node_2:
    image: symetric-quorum-node
    environment:
      - KEEP_FILES=false
      - NODE_NAME=node2
      - CONSENSUS=istanbul
      - IP=172.14.0.3
      - COORDINATING_IP=172.14.0.2
      - ROLE=dynamicPeer
      - DEPENDENT_IP=172.14.0.2
    links:
      - "node_1:node_1"
    networks:
      three_node_quorum:
        ipv4_address: '172.14.0.3'
  node_3:
    image: symetric-quorum-node
    environment:
      - KEEP_FILES=false
      - NODE_NAME=node3
      - CONSENSUS=istanbul
      - IP=172.14.0.4
      - COORDINATING_IP=172.14.0.2
      - ROLE=dynamicPeer
      - DEPENDENT_IP=172.14.0.3
    links:
      - "node_1:node_1"
    networks:
      three_node_quorum:
        ipv4_address: '172.14.0.4'

networks:
  three_node_quorum:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.14.0.0/16


# Running the following 2 commands consecutively should create a two node network (this assumes that you alreday have a docker network called examples_two_node_quorum):

# docker run --name n1 --network=examples_two_node_quorum --ip=172.14.0.5 \
# -e KEEP_FILES='false' \
# -e NODE_NAME='node1' \
# -e CONSENSUS='istanbul' \
# -e ROLE='coordinator' \
# -e IP='172.14.0.5' \
# symetric-quorum-node

# docker run --name n2 --network=examples_two_node_quorum --ip=172.14.0.6 \
# -e KEEP_FILES'=false' \
# -e NODE_NAME'=node2' \
# -e CONSENSUS'=istanbul' \
# -e IP'=172.14.0.6' \
# -e COORDINATING_IP'=172.14.0.5' \
# -e ROLE'=dynamicPeer' \
# -e DEPENDENT_IP'=172.14.0.5' \
# symetric-quorum-node
